FROM mirror.gcr.io/python:3.11

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

EXPOSE 8001

COPY . .

CMD [ "uvicorn", "main:app", "--port", "8001", "--host", "0.0.0.0", "--reload" ]