services:
  vault:
    build: 
      dockerfile: Dockerfile.prod.vault
      context: .
    ports:
      - 8001:8001
    volumes:
      - ./settings.json:/app/settings.json
    env_file:
      - .env
    restart: always

  postgres:
    build: 
      dockerfile: Dockerfile.postgres
      context: .
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
    restart: always

  redis:
    image: mirror.gcr.io/redis:7.4
    restart: always
    volumes:
      - redisdata:/data



volumes:
  pgdata:
  redisdata: