services:
  backend:
    build: 
      dockerfile: Dockerfile.vault
      context: .
    ports:
      - 8000:8000
    volumes:
      - ${PWD}/settings.json:/app/settings.json:rw
    networks:
      - default
      - vault-network
    restart: always

  postgres:
    build: 
      dockerfile: Dockerfile.postgres
      context: .
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
    restart: always

  redis:
    image: mirror.gcr.io/redis:7.4
    restart: always
    volumes:
      - redisdata:/data



volumes:
  pgdata:
  redisdata:

networks:
  vault-network:
    external: true
