name: Deploy on push to main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files to server
      run: |
        rsync -avz --exclude='.git' --exclude='.github' -e "ssh -o StrictHostKeyChecking=no" . ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home/${{ secrets.SERVER_USER }}/app/
    
    - name: Check and Create Docker Network
      run: |
        NETWORK_NAME="vault-network"
        if ! docker network inspect $NETWORK_NAME >/dev/null 2>&1; then
          echo "Network $NETWORK_NAME does not exist. Creating it..."
          docker network create $NETWORK_NAME
        else
          echo "Network $NETWORK_NAME already exists. Skipping creation."
        fi

    - name: Run docker compose on server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          cd /home/${{ secrets.SERVER_USER }}/app
          source .env
          sudo docker compose -f docker-compose.prod.yml down
          sudo docker compose -f docker-compose.prod.yml pull
          sudo docker compose -f docker-compose.prod.yml up -d --build
        EOF